### ISSUE TITLE
The keyboard

### ISSUE THREAD

**Issue by Techokami** [leomil72/LM80C#1]
This is an interesting project! My only concern is the keyboard module choice. While there were Commodore 16 keyboard modules sold via surplus back in the 80s and 90s, that was... back in the 80s and 90s, and the store that sold them is no longer around (RIP Radio Shack), so getting these modules is very unreliable and can get expensive on eBay. From what I've seen, it's just a matrix of switches, but it would be really nice to have the connector and the matrix documented in this repository, so that someone could develop a keyboard module with modern parts for it...

**Comment by leomil72** [comment]
Hello. Since this is a sort of replica of an old 8-bit computer I've tried to used components of that era, like the keyboard. You could try some auction sites around the web, it wouldn't be difficult to find a non working computer from which cannibalize some parts, like the keyboard, for a modest amount of money. Or, if you're lucky, just the keyboard, as I got it. 
BTW your suggestion is valid and I will add the keys' matrix so that anyone will be able to do a keyboard module.
