### ISSUE TITLE
daisy chain priority

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#10]
I can't find any reference on the docs about the daisy chain interrupt priority. From the schematics I deduced `SIO` has the highest priority, then `CTC`, and lastly `PIO`. Is that so (or it's reversed?)

**Comment by leomil72** [comment]
The priority is hard-wired. The periphery chip that has its IEI pin connected to +5V is the highest one. On the LM80C, this is the SIO; then there is the CTC, then PIO, as you pointed out. I decided so because IMHO incoming data through serial must be served as soon as they are available. Then CTC, because it's the system tick counter. Theh the PIO, because at the moment it isn't very useful... just used to turn on some LEDs. I will add some reference in future releases of the docs.
