### ISSUE TITLE
question about timing the TMS9918

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#15]
I have a question about the access timings for the VDP. I noticed in your firmware code you put three `NOP`s between VDP accesses. But checking the TMS9918 manual (see below) it talks about a 8μs delay which would be 8 nops.

I derived the number from this calculation:
- Z80 clock period is 1/3.6864 ≈ 0.271 μs
-  8μs / 0.271 ≈ 30 Z80 clock cycles. 
- in `NOP` terms, 30 / 4 ≈ 8 nops

Since your code actually works, what am I missing ? :smile: It would be nice to emulate such strict timings in order to check if a program can run on a real LM80C.

![image](https://user-images.githubusercontent.com/2598443/80945135-69cb8d00-8deb-11ea-8eff-c5415f79cd7b.png)

**Comment by leomil72** [comment]
I think you're missing the time required by the CPU to execute the rest of the instructions.
Let me explain you. Let us consider the "READ_VIDEO_LOC" sub into VDP.ASM. If you look at the code you see:
`                out     (C),L           ; low byte then...`
`                out     (C),B           ; high byte`
`                ld      C,VDP_DAT       ; VDP data mode`
`                nop                     ; wait...`
`                nop                     ; ...a while`
`                nop`
`                in      A,(C)           ; read byte at current VRAM location`
The count start after the execution of the second OUT instruction.
Then there are:
LD C + NOP + NOP + NOP + IN
7+4+4+4+12 = 31 T states
Yes, IN shouldn't be considered in its entirety since only in its first part (M1 cycle and maybe a part of M2) the CPU is setting up the address on the address bus and sending the signals to the VDP. BTW, this seems to be enough for the VDP.

**Comment by nippur72** [comment]
oh great explanation, thanks! It makes sense now. 👍
