### ISSUE TITLE
INKEY(0) sometimes lags

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#18]
```
10 a=inkey(0)
20 if a<>0 then print a
30 goto 10
```
when pressing random keys on the keyboard it seldom skips groups of keys for about 1-2 seconds and then it does resume detecting key presses. 

Try for example pressing `Z` 20 times at about 1/2 secs intervals. 

It doesn't happen if you have a longer time period e.g. `INKEY(100)`.  Assuming it's not emulator issue, my guess it that the `INKEY` routine is eating unprocessed characters at the end of the routine (`ENDINK`).

Can you reproduce this issue on the real machine?

**Comment by leomil72** [comment]
I confirm it. There's something buggy...

**Comment by leomil72** [comment]
I revised a bit the INKEY code. While INKEY(0) hasn't been changed (it's not meant to be used to read the keyboard buffer continuosly but just to discard the key preivously pressed, if present), I changed the INKEY statement so that now only accepts a minimum interval of 10 hundredths of a second.
The correct sequence to wait for a key is:
```
10 A=INKEY(0):REM ONLY USED TO DISCARD THE LAST CHAR
20 A=INKEY(10):IF A=0 THEN 20
```
The new behaivor is in R3.13
