### ISSUE TITLE
KEY command converts to uppercase

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#24]
```
key 8, "aaa"
```
sets the key to `AAA` (uppercase) instead of maintaining it lowercase.

Also, 
```
key 8, chr$(123)
```
produces a `?syntax error`

is this a desired behavior?

**Comment by leomil72** [comment]
You have to think a moment at the usage of the function keys: they are used to facilitate the input of common BASIC instructions and/or functions, not just to print funny chars over the screen.

So, KEY is used to assign some useful statements used in BASIC, and its code converts each char from 'a' to 'z' to uppercase since BASIC statements are always listed in uppercase. Similarly, it doesn't accept strange chars that could lead to strange behaviors of the interpreter. This is the reason why it doesn't accept ASCII codes under 32 (the space) and over 122 (the 'z').

PS: if you want to print the '{' and '}' chars they are already present onto the keyboard! Just use C= (the ALT key) and '[' and ']'.

**Comment by nippur72** [comment]
ok I thought it was a bug, because it's somewhat different than other BASICs (MSX, GW etc).
