### ISSUE TITLE
set cursor ON after keystroke

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#27]
When you navigate with the cursor keys across the screen, the cursor "vanishes" due to flashing; this makes it difficult to locate where the cursor is landing. 

I suggest to set the cursor to "ON" just after a key has been typed (C64 and others does it this way).

I tried to implement this feature myself but I found it difficult due to flashing based on timer rather than a counter.

**Comment by leomil72** [comment]
I discarded the usage of a separate counter for the cursor flashing because the interrupt routine is already doing a lot of stuff and it was easier to use a check on the system tick counter instead of overloading it with something more to do.
I agree that a flashing cursor while you're moving it isnt the best thing to see but it's simpler than other systems. Moreover, if you just set the cursor to ON after a key is being pressed, this does not mean that you'll have the cursor on for a long time since you could have pressed the key while the change of cursor status was about to happen.

**Comment by nippur72** [comment]
closing as it improved with v3.13.6
