### ISSUE TITLE
use INI / OUTI instructions in read/write sector loops

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#33]
I think you can save some bytes if you use the Z80 `INI` instruction in the read sector loop. 

I've seen it used in the BIOS of another system, I guess it's what `INI` was intended to be used for. 

E.g this:

```asm
LD C, CF_DATA
LD B,0
INI
INI
```

instead of:

https://github.com/leomil72/LM80C/blob/5f6643a43f6ee852ee0c1a6986f9ed6ba041aeaf/include/dos/bios-1.01.asm#L162-L168

Same for `OUTI`.

**Comment by leomil72** [comment]
In some cases, INI could be useful but, IMHO, not in this example. 
INI decrements B, too. But in that loop I need to load 2 bytes per cycle since a sector is 512 bytes wide and B can only counts up to 256. So using a couple of INI, one after the other, would lead to read only 256 bytes the same, due to B decremented twice. To solve it, I should add a mechanism to make a check with another register for 2 loops of 256 reads each, adding complexity to the code instead of simplifying it. I'm not sure it's profitable, I have to make some tests and count clock cycles and bytes for both cases. Anyway, thanks for the suggestion

**Comment by nippur72** [comment]
first I should correct myself because the instructions are `INIR` and `OUTIR`, not `INI` and `OUTI`.

That said, the 512 bytes read should be handled automatically because the `B` register goes down to 0 twice while still writing into `(HL)` and incrementing `HL`.

I wrote a small patch that I tried in the emulator, you can test it in the real machine and see if it's good for the CF card timings:

```basic
10 DATA 14,80    
20 DATA 237,178   
30 DATA 237,178   
40 DATA 0,0,0,0              
50 FOR T=0 TO 9 
60 READ B
70 POKE &H10AC+T,B
80 NEXT
```

The patch code is:
```
ORG $10AC ; points in the firmware
LD C, CF_DATA
INIR
INIR
NOP ; filler
NOP ;
NOP ;
NOP ;
```

I think one more additional byte can be saved if you load `B` and `C` at the same time, e.g. `LD BC, CF_DATA`

**Comment by leomil72** [comment]
It seems to work. In the past I tried using INIR and OTIR but I experienced several issues so I decomposed those instructions into slower portion of codes but, clearly, there was something more that interfered with the I/O operations. I'll add these enhanchements into the next release.
