### ISSUE TITLE
RUN STOP doesn't stop a program

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#8]
the `RUN STOP` key doesn't stop a running BASIC program (but `ESC` does it).

It would be nice if you also supported `SHIFT` + `RUN STOP` for "RUN", moving it out of KEY #2.

**Comment by leomil72** [comment]
Is it `RUN STOP` key or are you using the `CTRL+C` shortcut?
Because in the real machine, it does stop the program.

**Comment by leomil72** [comment]
> It would be nice if you also supported `SHIFT` + `RUN STOP` for "RUN", moving it out of KEY #2.

It was a decision of my own: I prefer to look at that key as "RUN STOP" instead of "RUN/STOP", meaning that I just needed a key to halt the program. And it's like on the real C16, where "RUN" was also present between the FN keys.

**Comment by nippur72** [comment]
ok, it was an emulator bug--actually a bug in the browser: I had mapped `RUN STOP` to `Pause` but on Chrome the event for keypress up is fired just after the "down" not giving time to the firmware to catch it. Remapped it to `Tab`.

**Comment by leomil72** [comment]
Since I have no memory about the use of SHIFT+RUN/STOP to run a program on my C16, I checked the user's manual and found confirms of this. In fact, on the C16 the SHIFT+RUN/STOP shortcut loaded and ran the first program found on a disk inside the disk drive but since I never had this device I never used this shortcut :-)
I think it's a C64 legacy...
