### ISSUE TITLE
NMI interrupt can't use VDP ?

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#9]
I finally managed to write a program that uses the NMI interrupt with the new firmware. I discovered the hard way that the VDP needs to be acknowledged of the end of the interrupt by the read of the status register; otherwise it won't trigger another interrupt.

Below you'll find the program I wrote, could you please execute it on the real LM80C and send me back a picture of the screen? I need it to verify the accuracy of the emulator.

Anyway there seems to be a big issue with the NMI in general. When I run the above program and scroll the video (e.g. `LIST`), the screen gets scrambled and after a while the LM80C behaves erratically.

I suspect this is due to the NMI interrupting just when the firmware is accessing the VDP; it doesn't matter that all the VDP ops are enclosed in `DI` and `EI`, it's a NMI and you can't stop it. Is that correct?

I tried to remove all VDP writes in the routine (except of course the INT ACK) and indeed it does work normally. So I deduce this means that only one routine can use the VDP: the NMI routine or the outside-NMI.

In this scenario I think that the NMI hook is still useful for games when an hypothetical game loop is all within the NMI routine.  For raster tricks, the NMI could be used as a reference for CTC and make all video updates in the CTC-triggered interrupt which is maskable.

What are your comments?

```
10 FOR T=&H9000 TO &H9037
20 READ B:POKE T,B
30 NEXT
40 SYS &H9000
50 END
1000 DATA 17,6,144,195,23,38,245,213
1010 DATA 229,30,246,62,7,205,19,6
1020 DATA 33,218,2,205,50,144,30,247
1030 DATA 62,7,205,19,6,33,0,5
1040 DATA 205,50,144,30,244,62,7,205
1050 DATA 19,6,205,30,6,225,209,241
1060 DATA 237,69,43,125,180,32,251,201
```

the source:
```
org $9000
INSTALL:
   LD DE, MYROUTINE
   JP $2617   ; NMI basic command

MYROUTINE:
   push af
   push de
   push hl

   ld   e, $F6
   ld   a, $07
   call WRITE_VREG

   ld   hl, $02da
   call wait

   ld   e, $F7
   ld   a, $07
   call WRITE_VREG

   ld   hl, $0500
   call wait

   ld   e, $F4
   ld   a, $07
   call WRITE_VREG

   call READ_VSTAT         ; ACK NMI by reading the VDP status register

   pop hl
   pop de
   pop af

   RETN

wait:
   dec  hl
   ld   a, l
   or   h
   jr   nz, wait
   ret
```

and what you should see: 
![image](https://user-images.githubusercontent.com/2598443/80794125-5f19b980-8b99-11ea-985f-43825d834cff.png)

**Comment by leomil72** [comment]
Attached the required screenshot.
Let me say that:
1) there are more glitches than in yours, because the real TMS has very mandatory timings to access data that is to/from VRAM so it goes crazy very easily; system is responding very slowly, when I type some RETURNs the screen start going mad. BTW, the interpreter is still responding since I see correct messages from the BASIC over the serial port. If I give a NMI 0 to detouch the NMI, everything returns normal.
2) you're right when you say that NMI is not practical as you thinked about it because TMS is very particular in its way of communicating with the CPU. So, It needs that the double-byte transfer of the command must be done with no breaks: if, after the firts OUT, another operation is sent to the VDP, it losts the point of the previous one that was doing. So, when you point at the fact that during a READ/WRITE, even if operations are between EI/DI, something weird ahppens, you got the problem. LM80C has been developed in a way that didn't use the NMI signal to do its stuff beause I chose to use IM2, to be able to manage INTs from the peripheral chips in an easy way. The only way to change everything is to... change everything and write the interrupt service routine from scratch, a way I don't even want to keep in consideration... 
![IMG_6193](https://user-images.githubusercontent.com/1081865/80800643-4239b200-8baa-11ea-8fde-ff6f3d57ae58.JPG)

**Comment by nippur72** [comment]
Ok, thank you for the test image, I checked again the numbers and now I'm able to get a very similar picture as yours.

The actual numbers are:
VDP clock: 10,700,000 Hz (as per your schematic)
Number of dot pixel per image: 342 x 262 x 2 (as per TMS data sheet) 
Resulting refresh rate: 59.7071559305 Hz
CPU speed = 7,700,000 / 2 = 3,685,000 Hz (as per your schematic)
CPU clock cycles per line = 235.5644859

Regarding the CPU clock, you once mentioned it to be 3686400, not 3685000, which number is correct?

The aligned image compared with your:
![image](https://user-images.githubusercontent.com/2598443/80811008-563edd00-8bc5-11ea-97b3-e1712ced7f19.png)

I'm also able to get the same glitches as you, which means that the emulation is pretty good :smile:
![image](https://user-images.githubusercontent.com/2598443/80810117-6f468e80-8bc3-11ea-9cf4-06d6c630ff76.png)

My thought on the NMI is that it can be useful under certain circumstances, we have just to keep in mind the VDP limitation. Perhaps I wouldn't keep the dedicated `NMI` BASIC command, but since it's already there...

A simple useful NMI routine is to have a counter that increments at every interrupt. A game loop then keeps watching the counter until it changes:
```
NMIROUTINE:
   PUSH HL
   LD HL, counter
   INC (HL)
   POP HL
   CALL READ_VSTAT
   RETN

GAME_LOOP:
   ....
   LD HL, counter
   LD A, (HL)
WAIT:
   XOR (HL)
   JR Z, WAIT
   ; screen updates here
   JP GAME_LOOP
```

**Comment by leomil72** [comment]
The fact that the TMS emulator your're using is good is by far not in doubt! :-)
>A simple useful NMI routine is to have a counter that increments at every interrupt. A game loop then keeps watching the counter until it changes:

Keep in mind that this is already done by the sys tick counter: registers of TMR are incremented every 1/100th of a sec.

>Regarding the CPU clock, you once mentioned it to be 3686400, not 3685000, which number is correct?

The first one. I used a 7,372,800 Hz crystal, whose frequency is halved to 3,686,400 and used as system clock. Then this clock is halved again to get 1,843,200 Hz that is used as serial clock (and to clock the PSG sound chip, too).

As for the TMS, its clock is 10,738,635 Hz. This value is very mandatory, and referred into the VDP data sheet (because this value is 3 times the color burst clock  of an NTSC signal, 3.579545 MHz), with a very little tolerance.

Forget the roundings in the schematics and please give these values a try.

**Comment by nippur72** [comment]
thanks for the correct numbers, the image didn't change much as the error is within a scanline or so.

> 
> Keep in mind that this is already done by the sys tick counter: registers of TMR are incremented every 1/100th of a sec.
> 

yes of course but the whole point here is to wait where the raster is off-screen to avoid flicker and tearing. A smiliar thing is done in VIC20/C64, you wait til the bottom of the screen by watching the raster line register of the VIC chip. Here we don't have the exact line, but what matters is to know easily when the screen is at the bottom. Hopefully in the future we'll write some game that exploits all that.

**Comment by leomil72** [comment]
A lot of MSX games used the scanline interrupt of the TMS to move the sprites for smooth movements. Making a border rainbow is something more difficult since there is anything similar to the scanline register. You have to unravel with timings but with a different approch than yours (no delays into a NMI routine). Just start a counter of the CTC, then when this has reached the zero and raised its interrupt, make the change of the border color. To do this, you need to have the jump table for the CTC interrupts.... I think I will have to make this job...
